name: 'testResultsToMarkdown'
description: 'Parses a Nunit test result file and outputs a markdown table with the errors and failures'
author: 'corp-0'
inputs:
  testResultsFile:
    description: 'The path to the test results file'
    required: true
  onlyFailures:
    description: 'Only output failures and errors'
    required: false
    default: true
outputs:
  markdownText:
    description: 'The markdown table'
runs:
  using: 'node16'
  main: 'dist/index.js'
